services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - client
      - server
    restart: unless-stopped

  server:
    build: ./server
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build: ./client
    env_file:
      - ./client/.env
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=/api
    restart: unless-stopped
